### ISSUE TITLE
CakePHP 4 Support

### ISSUE THREAD

**Issue by josephshanak** [robotusers/cakephp-table-inheritance#8]
I am currently using this plugin in a CakePHP3 application that is preparing to upgrade to CakePHP 4, and I would like to know what your plans are for maintaining this plugin now that CakePHP 4 is out. Are there plans on updating this plugin to support CakePHP 4?

**Comment by robertpustulka** [comment]
@josephshanak Sorry fot he late response. I may at some point need this for CakePHP 4. But feel free to open a PR and make necessary changes for 4.x compatibility if you need this now and I will be happy to merge and release it.

**Comment by josephshanak** [comment]
@robertpustulka Here is a PR to add support for CakePHP4. Let me know if I need to do anything else there. I didn't see a contributing doc. https://github.com/robotusers/cakephp-table-inheritance/pull/9

**Comment by robertpustulka** [comment]
Resolved with #9
